
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int comillaS = 23;
  public static final int cadena = 5;
  public static final int corcheteC = 20;
  public static final int corcheteA = 19;
  public static final int coma = 3;
  public static final int ascii = 18;
  public static final int flecha = 17;
  public static final int concat = 13;
  public static final int separador = 16;
  public static final int conj = 4;
  public static final int rango = 8;
  public static final int comillaC = 24;
  public static final int or = 9;
  public static final int llaveC = 7;
  public static final int EOF = 0;
  public static final int llaveA = 6;
  public static final int id = 2;
  public static final int positiva = 11;
  public static final int error = 1;
  public static final int parentesisC = 22;
  public static final int parentesisA = 21;
  public static final int interrogacion = 12;
  public static final int klenee = 10;
  public static final int dospuntos = 14;
  public static final int puntoycoma = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "coma",
  "conj",
  "cadena",
  "llaveA",
  "llaveC",
  "rango",
  "or",
  "klenee",
  "positiva",
  "interrogacion",
  "concat",
  "dospuntos",
  "puntoycoma",
  "separador",
  "flecha",
  "ascii",
  "corcheteA",
  "corcheteC",
  "parentesisA",
  "parentesisC",
  "comillaS",
  "comillaC"
  };
}

